#!/usr/bin/env python3
"""Generate installer/windows/setup.iss from AppConfig constants.

Ensures the Inno Setup metadata stays in sync with the Python config.
Run from the project root:

    python installer/windows/generate_iss.py
"""
from __future__ import annotations

import os
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from src.config.settings import AppConfig

# ── Version resolution ──────────────────────────────────────────────────
# During CI builds the git tag is the single source of truth.
# BUILD_VERSION is set by the workflow; when absent (local/manual builds)
# we fall back to AppConfig.VERSION.

BUILD_VERSION: str = os.environ.get("BUILD_VERSION", "").strip()
if BUILD_VERSION:
    # Safety: fail early if the tag version doesn't match AppConfig.VERSION
    # so genuine version-bump mistakes are caught before the installer is built.
    if BUILD_VERSION != AppConfig.VERSION:
        print(
            f"ERROR: BUILD_VERSION ('{BUILD_VERSION}') does not match "
            f"AppConfig.VERSION ('{AppConfig.VERSION}').\n"
            f"Bump AppConfig.VERSION in src/config/settings.py to match "
            f"the git tag, or vice versa.",
            file=sys.stderr,
        )
        sys.exit(1)
    VERSION = BUILD_VERSION
else:
    VERSION = AppConfig.VERSION

TEMPLATE = r'''; ============================================================================
; Inno Setup Script — Hospital Management System
; ============================================================================
;
; AUTO-GENERATED by installer/windows/generate_iss.py
; Do NOT edit by hand — regenerate from AppConfig constants:
;
;   python installer/windows/generate_iss.py
;
; ============================================================================

; ── Metadata (mirrors AppConfig in src/config/settings.py) ───────────────
#define AppName         "{name}"
#define AppVersion      "{version}"
#define AppPublisher    "{publisher}"
#define AppCopyright    "{copyright}"
#define AppDescription  "{description}"

; ── Paths ────────────────────────────────────────────────────────────────
#define AppExeName      "HospitalScheduler.exe"
#define SetupExeName    "HMS-Setup.exe"
#define AppDirName      "HospitalScheduler"
#define IconFile        "..\\..\\assets\\icon.ico"
#define LicenseFile     "..\\..\\LICENSE"

; PyInstaller output directories (relative to project root)
#define MainDistDir     "..\\..\\dist\\HospitalScheduler"
#define SetupDistDir    "..\\..\\dist\\HMS-Setup"

[Setup]
; ── Identification ───────────────────────────────────────────────────────
AppId={{#AppName}}
AppName={{#AppName}}
AppVersion={{#AppVersion}}
AppPublisher={{#AppPublisher}}
AppCopyright={{#AppCopyright}}
AppPublisherURL=https://github.com/halo-sun/Hospital-Management-System
AppSupportURL=https://github.com/halo-sun/Hospital-Management-System/issues
AppUpdatesURL=https://github.com/halo-sun/Hospital-Management-System/releases

; ── Installation ─────────────────────────────────────────────────────────
DefaultDirName={{autopf}}\\{{#AppDirName}}
DefaultGroupName={{#AppName}}
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

; ── Output ───────────────────────────────────────────────────────────────
OutputDir=..\\..\\dist
OutputBaseFilename=HospitalScheduler-{{#AppVersion}}-Setup
Compression=lzma2
SolidCompression=yes
LZMANumBlockThreads=4

; ── Visual ───────────────────────────────────────────────────────────────
WizardStyle=modern
SetupIconFile={{#IconFile}}
UninstallDisplayIcon={{app}}\\{{#AppExeName}}
WizardImageFile=
WizardSmallImageFile=

; ── License ──────────────────────────────────────────────────────────────
LicenseFile={{#LicenseFile}}

; ── Misc ─────────────────────────────────────────────────────────────────
CloseApplications=force
RestartApplications=no
MinVersion=10.0.17763

[ Languages ]
Name: "english"; MessagesFile: "compiler:Default.isl"

[ Tasks ]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked

[ Files ]
; ── Main application ─────────────────────────────────────────────────────
Source: "{{#MainDistDir}}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

; ── Setup utility ────────────────────────────────────────────────────────
Source: "{{#SetupDistDir}}\\*"; DestDir: "{{app}}\\setup"; Flags: ignoreversion recursesubdirs createallsubdirs

[ Icons ]
; ── Start Menu ───────────────────────────────────────────────────────────
Name: "{{group}}\\{{#AppName}}"; Filename: "{{app}}\\{{#AppExeName}}"; Comment: "Launch Hospital Management System"
Name: "{{group}}\\Database Setup"; Filename: "{{app}}\\setup\\{{#SetupExeName}}"; Comment: "Run database setup wizard"
Name: "{{group}}\\{{cm:UninstallProgram,{{#AppName}}}}"; Filename: "{{uninstallexe}}"

; ── Desktop (optional) ──────────────────────────────────────────────────
Name: "{{autodesktop}}\\{{#AppName}}"; Filename: "{{app}}\\{{#AppExeName}}"; Tasks: desktopicon

[ Run ]
; ── Launch HMS-Setup.exe after installation ──────────────────────────────
Filename: "{{app}}\\setup\\{{#SetupExeName}}"; \\
    Description: "Set up the database now (recommended)"; \\
    Flags: postinstall skipifsilent nowait

; ── Optionally launch the main app ──────────────────────────────────────
Filename: "{{app}}\\{{#AppExeName}}"; \\
    Description: "Launch {{#AppName}}"; \\
    Flags: postinstall skipifsilent nowait unchecked

[ UninstallDelete ]
; Remove logs created by the application (but NOT user data by default)
Type: filesandordirs; Name: "{{app}}\\logs"
Type: filesandordirs; Name: "{{app}}\\reports"
Type: filesandordirs; Name: "{{app}}\\exports"

[ Code ]
// ── Uninstall: ask about removing user data ────────────────────────────
// The %LOCALAPPDATA%\\HospitalScheduler directory contains uploaded
// patient documents, logs, and reports.  Deleting this without very
// explicit confirmation would be a data-loss risk, so we default to
// LEAVING it in place and only offer removal if the user confirms.

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
    AppDataDir: String;
    ResultCode: Integer;
begin
    if CurUninstallStep = usPostUninstall then
    begin
        // Build the user data path (same logic as the app's _user_data_dir)
        AppDataDir := ExpandConstant('{{localappdata}}\\HospitalScheduler');

        if DirExists(AppDataDir) then
        begin
            if MsgBox(
                'The application data directory still exists:'#13#10 +
                AppDataDir + #13#10#13#10 +
                'This contains uploaded patient documents, logs, and reports.'#13#10#13#10 +
                'Do you want to REMOVE this directory and all its contents?'#13#10 +
                '(Select No to keep your data.)',
                mbConfirmation,
                MB_YESNO or MB_DEFBUTTON2
            ) = IDYES then
            begin
                DelTree(AppDataDir, True, True, True);
                MsgBox('Data directory removed.', mbInformation, MB_OK);
            end
            else
            begin
                MsgBox(
                    'Data directory kept at:'#13#10 + AppDataDir + #13#10#13#10 +
                    'You can delete it manually later if needed.',
                    mbInformation, MB_OK
                );
            end;
        end;
    end;
end;
'''.format(
    name=AppConfig.NAME,
    version=VERSION,
    publisher=AppConfig.PUBLISHER.replace("&", "&&"),  # Inno Setup uses && for literal &
    copyright=AppConfig.COPYRIGHT.replace("&", "&&"),
    description=AppConfig.APP_DESCRIPTION,
)


def main() -> None:
    out_path = os.path.join(PROJECT_ROOT, "installer", "windows", "setup.iss")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(TEMPLATE)
    print(f"Generated {out_path}")
    print(f"  AppName:    {AppConfig.NAME}")
    print(f"  Version:    {VERSION}")
    print(f"  Publisher:  {AppConfig.PUBLISHER}")
    print(f"  Copyright:  {AppConfig.COPYRIGHT}")


if __name__ == "__main__":
    main()
